openapi: 3.0.1
info:
  title: FIAP-API
  description: ''
  version: 1.0.0
tags:
  - name: Aluno
  - name: Turma
  - name: Matricula
  - name: createAluno
  - name: listAlunos
  - name: listaAlunoId
  - name: updateAluno
  - name: inactivateAluno
  - name: activateAluno
  - name: deleteAluno
paths:
  /api/aluno:
    post:
      summary: Cria um aluno
      deprecated: false
      description: ''
      tags:
        - Aluno
        - createAluno
      parameters:
        - name: usuario
          in: query
          description: ''
          required: true
          example: R123
          schema:
            type: string
        - name: nome
          in: query
          description: ''
          required: true
          example: pamela
          schema:
            type: string
        - name: sobrenome
          in: query
          description: ''
          required: true
          example: tossato
          schema:
            type: string
        - name: data_nascimento
          in: query
          description: ''
          required: true
          example: 09/07/1996
          schema:
            type: string
        - name: status
          in: query
          description: ''
          required: true
          example: ativo
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    get:
      summary: Lista todos os Alunos
      deprecated: false
      description: ''
      tags:
        - Aluno
        - listAlunos
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/aluno/3:
    get:
      summary: Lista um Aluno pelo id
      deprecated: false
      description: ''
      tags:
        - Aluno
        - listaAlunoId
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/aluno/1:
    put:
      summary: Atualiza o aluno
      deprecated: false
      description: ''
      tags:
        - Aluno
        - updateAluno
      parameters:
        - name: usuario
          in: query
          description: ''
          required: false
          example: R123
          schema:
            type: string
        - name: nome
          in: query
          description: ''
          required: false
          example: pamela
          schema:
            type: string
        - name: sobrenome
          in: query
          description: ''
          required: false
          example: tossato
          schema:
            type: string
        - name: data_nascimento
          in: query
          description: ''
          required: false
          example: 09/07/1996
          schema:
            type: string
        - name: status
          in: query
          description: ''
          required: false
          example: ativo
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    delete:
      summary: Deleta o Aluno
      deprecated: false
      description: ''
      tags:
        - Aluno
        - deleteAluno
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/aluno/1/inactivate:
    patch:
      summary: Inativa o Aluno
      deprecated: false
      description: ''
      tags:
        - Aluno
        - inactivateAluno
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/aluno/1/activate:
    patch:
      summary: Ativa o Aluno
      deprecated: false
      description: ''
      tags:
        - Aluno
        - activateAluno
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/turma/1:
    get:
      summary: Lista uma Turma pelo id
      deprecated: false
      description: ''
      tags:
        - Matricula
        - listaAlunoId
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    delete:
      summary: Deleta o Aluno
      deprecated: false
      description: ''
      tags:
        - Turma
        - deleteAluno
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    put:
      summary: Atualiza a turma
      deprecated: false
      description: ''
      tags:
        - Turma
        - updateAluno
      parameters:
        - name: nome
          in: query
          description: ''
          required: false
          example: ADS
          schema:
            type: string
        - name: descricao
          in: query
          description: ''
          required: false
          example: Curso Análise de Sistema
          schema:
            type: string
        - name: tipo
          in: query
          description: ''
          required: false
          example: Presencial
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/turma:
    post:
      summary: Cria uma turma
      deprecated: false
      description: ''
      tags:
        - Turma
        - createAluno
      parameters:
        - name: nome
          in: query
          description: ''
          required: true
          example: ADS
          schema:
            type: string
        - name: descricao
          in: query
          description: ''
          required: true
          example: Curso análise de sistema
          schema:
            type: string
        - name: tipo
          in: query
          description: ''
          required: true
          example: EAD
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    get:
      summary: Lista todas as Turmas
      deprecated: false
      description: ''
      tags:
        - Turma
        - listAlunos
      parameters:
        - name: turma
          in: query
          description: ''
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/matricula/aluno/1:
    get:
      summary: Lista todas as Turmas de um Aluno
      deprecated: false
      description: ''
      tags:
        - Matricula
        - listAlunos
      parameters:
        - name: turma
          in: query
          description: ''
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/matricula/turma/1:
    get:
      summary: Lista todas os Alunos de uma Turma
      deprecated: false
      description: ''
      tags:
        - Matricula
        - listAlunos
      parameters:
        - name: turma
          in: query
          description: ''
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /api/matricula:
    post:
      summary: Cria uma relacao de matricula
      deprecated: false
      description: ''
      tags:
        - Matricula
        - createAluno
      parameters:
        - name: id_aluno
          in: query
          description: ''
          required: true
          example: 1
          schema:
            type: integer
        - name: id_turma
          in: query
          description: ''
          required: true
          example: 1
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    put:
      summary: Atualiza a turma do aluno
      deprecated: false
      description: ''
      tags:
        - Matricula
        - updateAluno
      parameters:
        - name: id_aluno
          in: query
          description: ''
          required: false
          example: 1
          schema:
            type: integer
        - name: id_turma
          in: query
          description: ''
          required: false
          example: 1
          schema:
            type: integer
        - name: nova_turma
          in: query
          description: ''
          required: false
          example: 2
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
    delete:
      summary: Deleta a matricula
      deprecated: false
      description: ''
      tags:
        - Matricula
        - deleteAluno
      parameters:
        - name: id_aluno
          in: query
          description: ''
          required: false
          example: 1
          schema:
            type: integer
        - name: id_turma
          in: query
          description: ''
          required: false
          example: 2
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers:
  - url: https://dev.your-api-server.com
    description: Amb. de desenv.
